# Homework 1: 

##  Introduction to Machine Learning for Machine Learning Zoomcamp 2026
___

#### Downloainding the data from the link provided in the homework description

In [29]:
# Import the library
import pandas as pd
import numpy as np
import requests

In [30]:
# URL of the file to be downloaded
url = 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv'

# Send a GET request to the URL
response = requests.get(url)

# Save the downloaded content to a local file in this directory
with open('car_fuel_efficiency_2026.csv', 'wb') as f:
    f.write(response.content)

# Load the local file into a pandas DataFrame
df = pd.read_csv('car_fuel_efficiency_2026.csv')

# Display the first few rows of the DataFrame
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

####  Import the pandas library

In [ ]:
import pandas as pd
pd.__version__

In [32]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [33]:
# checking info about the data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 1.1 MB

____

####  Question 1. Pandas version (1 point)

In [34]:
# Question 1. Pandas version (1 point)
pd.__version__

'3.0.6'

#### Question 2. How many records are in the dataset?

In [35]:
# Question 2. Records count (1 point) Number of rows in the dataset
num_columns = df.shape[0]
print(num_columns)

10000

#### Question 3. How many fuel types are presented in the dataset?

In [36]:
# Question 3. Fuel types (1 point)
num_fuel_types = df['fuel_type'].nunique()
num_fuel_types

3

#### Question 4.How many columns in the dataset have missing values?

In [37]:
# Question 4. Missing values (1 point)
missing_values = df.isnull().sum()
missing_values

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [38]:
# Count of columns that have at least one missing value
columns_with_missing = (missing_values > 0).sum()
columns_with_missing

np.int64(2)

#### Question 5. What's the maximum fuel efficiency of cars from Asia?

In [39]:
# Question 5. Max fuel efficiency of cars from Asia (1 point)
max_fuel_efficiency_asia = df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()
max_fuel_efficiency_asia

np.float64(41.2)

####  Question 6. Median value of horsepower (1 point)

- Find the median value of the `horsepower` column in the dataset.
- Next, calculate the most frequent value of the same `horsepower` column.
- Use fillna method to fill the missing values in `horsepower` column with the most frequent value from the previous step.
- Now, calculate the median value of `horsepower` once again.
- Has it changed?

In [40]:
# Find the median value of horsepower column in the dataset.
median_horsepower = df['horsepower'].median()
median_horsepower

np.float64(254.0)

In [42]:
# Next, calculate the most frequent value of the same horsepower column.
most_frequent_horsepower = df['horsepower'].mode()[0]
most_frequent_horsepower

np.float64(252.0)

In [49]:
# Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
df['horsepower'] = df['horsepower'].fillna(most_frequent_horsepower)

df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower               0
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [50]:
# Now, calculate the median value of horsepower once again.
median_horsepower_after = df['horsepower'].median()
median_horsepower_after

np.float64(252.0)

#### Question 7. Sum of weights (1 point)

- Select all the cars from Asia.
- Select only columns `vehicle_weight` and `model_year`.
- Select the first 7 values.
- Get the underlying NumPy array. Let's call it X.
- Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
- Invert XTX.
- Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
- Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
- What's the sum of all the elements of the result?

In [44]:
# Select all the cars from Asia.
asia_cars = df[df['origin'] == 'Asia']
asia_cars

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [45]:
# Select only columns vehicle_weight and model_year, then the first 7 values.
column_select = ['vehicle_weight', 'model_year']
data = asia_cars[column_select].head(7)
data

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [46]:
# Get the underlying NumPy array. Let's call it X.
X = data.values

# Print the NumPy array,and check the shape of the array.
print(X)
print(X.shape)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]
(7, 2)

In [47]:
# compute the transpose of the NumPy array X and assign it to the variable X_tranpose.
X_tranpose = X.T

# Print the transposed array, and the shape of the transposed array.
print(X_tranpose)
print(X_tranpose.shape)

[[4240 4310 4230 4420 3950 4750 4450]
 [1996 1992 1997 1978 2007 2021 2019]]
(2, 7)

In [48]:
# Compute matrix-matrix multiplication between the transpose of X and X to get a square matrix
XTX = X_tranpose @ X
print(XTX)

# shape of the resulting matrix
shape_XTX = XTX.shape
shape_XTX

[[131950500  60750580]
 [ 60750580  28041424]]

(2, 2)

In [51]:
# Compute the inverse of the XTX array and assign it to the variable XTX_inv
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

In [52]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [53]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

w = XTX_inv @ X_tranpose @ y
print(w)

[0.13644777 0.2327492 ]

In [54]:
# - What's the sum of all the elements of the result?

sum_w = w.sum()
print(sum_w)

0.36919696904925203